<template>
	<Dialog :open="isOpen" @update:open="closeModal">
		<DialogContent
			class="w-[94vw] sm:max-w-3xl max-h-[90dvh] p-0 flex flex-col overflow-hidden"
		>
			<div class="border-b px-4 py-3 sm:px-5">
					<DialogHeader>
						<DialogTitle
							>{{ isEditing ? "Edit" : "Create" }}
							{{ dataTypeLabel }}</DialogTitle
						>
						<DialogDescription>
							{{ modalDescription }}
						</DialogDescription>
					</DialogHeader>
				</div>

			<!-- Form -->
			<form @submit.prevent="saveItem" class="flex-1 flex flex-col min-h-0">
				<div class="flex-1 min-h-0 overflow-y-auto px-4 sm:px-5">
					<div class="py-3 space-y-4">
							<div
								v-for="(section, sectionIndex) in formSections"
								:key="section.key"
								:class="[
									sectionIndex > 0 ? 'border-t border-border/60 pt-3' : '',
									'space-y-3',
								]"
							>
								<div
									v-if="section.key === 'optional'"
									class="flex items-center justify-between gap-3"
								>
									<h3 class="text-sm font-medium tracking-tight text-foreground">
										{{ section.title }}
									</h3>
									<Button
										type="button"
										variant="ghost"
										size="sm"
										class="h-9 px-2"
										@click="toggleOptionalSection(section.key)"
									>
										{{ isOptionalSectionOpen(section.key) ? "Hide" : "Show" }}
									</Button>
								</div>
								<div v-else>
									<h3 class="text-sm font-medium tracking-tight text-foreground">
										{{ section.title }}
									</h3>
								</div>

								<div
									v-if="section.key !== 'optional' || isOptionalSectionOpen(section.key)"
									:class="[
										'grid grid-cols-1 gap-3 sm:gap-4',
										useSingleColumnLayout ? '' : 'lg:grid-cols-2',
									]"
								>
									<div
										v-for="field in section.fields"
										:key="field.key"
										:class="
											field.fullWidth && !useSingleColumnLayout ? 'lg:col-span-2' : ''
										"
									>
											<div v-if="field.type === 'text' && !isSubCategoryAsyncField(field)">
												<FormFieldLabel
													:field-key="field.key"
													:label="field.label"
													:required="field.required"
													:description="getFieldDescription(field.key)"
												/>
												<Input
												:id="field.key"
												v-model="formData[field.key]"
												:placeholder="field.placeholder"
												:required="field.required"
												:readonly="isAutoGeneratedIdField(field.key)"
												:disabled="
													isEditing &&
													props.dataType === 'problems' &&
													field.key === 'sub_category_id'
												"
												:class="[
													'mt-1 h-11',
													isAutoGeneratedIdField(field.key)
														? 'bg-muted cursor-not-allowed'
														: '',
												]"
													@blur="handleValidationBlur(field.key)"
												/>
												<p
													v-if="isAutoGeneratedIdField(field.key)"
													class="mt-1 text-sm leading-6"
													:class="
														systemIdError ? 'text-destructive' : 'text-muted-foreground'
													"
												>
													{{
														isGeneratingSystemId
															? "Generating ID automatically..."
															: systemIdError || "Generated automatically. You can keep this value."
													}}
												</p>
											</div>

										<div v-else-if="field.type === 'textarea'">
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
												:required="field.required"
												:description="getFieldDescription(field.key)"
											/>
											<Textarea
												:id="field.key"
												v-model="formData[field.key]"
												:rows="field.rows || 3"
												:placeholder="field.placeholder"
												:required="field.required"
												class="mt-1"
											/>
										</div>

										<div
											v-else-if="
												field.type === 'select' &&
												!(
													props.dataType === 'assessments' &&
													field.key === 'sub_category_id'
												)
											"
										>
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
												:required="field.required"
												:description="getFieldDescription(field.key)"
											/>
											<Select
												v-model="formData[field.key]"
												:required="field.required"
											>
												<SelectTrigger class="mt-1 h-11 w-full">
													<SelectValue
														:placeholder="field.placeholder || 'Select an option'"
													/>
												</SelectTrigger>
												<SelectContent>
													<template v-if="field.options && field.options.length">
														<SelectItem
															v-for="option in field.options"
															:key="option.value"
															:value="option.value"
														>
															{{ option.label }}
														</SelectItem>
													</template>
													<template
														v-else-if="
															field.key === 'sub_category_id' &&
															dropdownOptions.sub_category_id &&
															dropdownOptions.sub_category_id.length
														"
													>
														<SelectItem
															v-for="option in dropdownOptions.sub_category_id"
															:key="option.value"
															:value="option.value"
														>
															{{ option.label }}
														</SelectItem>
													</template>
												</SelectContent>
											</Select>
										</div>

										<div v-else-if="isSubCategoryAsyncField(field)">
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
												:required="field.required"
												:description="getFieldDescription(field.key)"
											/>
											<AsyncSearchSelect
												v-model="formData.sub_category_id"
												:input-id="field.key"
												table-name="problems"
												:search-fields="[
													'sub_category_id',
													'problem_name',
													'category',
													'description',
												]"
												value-field="sub_category_id"
												:display-fields="['sub_category_id', 'problem_name']"
												:placeholder="
													props.dataType === 'suggestions'
														? 'Search subcategories by ID or name'
														: 'Type to search subcategories by ID, category, or description'
												"
												fetch-url="/dataset/problems/subcategories"
											/>
										</div>

										<div v-else-if="field.type === 'tags'">
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
												:required="field.required"
												:description="getFieldDescription(field.key)"
											/>
											<div class="mt-1">
												<div class="mb-2 flex flex-wrap gap-2">
													<Badge
														v-for="(tag, index) in formData[field.key] || []"
														:key="index"
														variant="secondary"
														class="flex items-center gap-1"
													>
														{{ tag }}
														<button
															type="button"
															@click="removeTag(field.key, index as number)"
															class="-m-1 inline-flex h-11 w-11 items-center justify-center rounded-full hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
															:aria-label="`Remove tag ${tag}`"
														>
															<X class="h-3 w-3" />
														</button>
													</Badge>
												</div>
												<div class="flex flex-col gap-2 sm:flex-row">
													<Input
														v-model="newTag[field.key]"
														:placeholder="field.placeholder"
														class="h-11 flex-1"
														@keydown.enter.prevent="addTag(field.key)"
														@keydown.comma.prevent="addTag(field.key)"
													/>
													<Button
														type="button"
														variant="outline"
														@click="addTag(field.key)"
														class="h-11 w-full sm:w-auto"
													>
														Add
													</Button>
												</div>
											</div>
										</div>

										<div
											v-else-if="
												field.type === 'number' &&
												!(
													props.dataType === 'assessments' &&
													(field.key === 'scale_min' ||
														field.key === 'scale_max') &&
													!showScaleFields
												)
											"
										>
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
												:required="field.required"
												:description="getFieldDescription(field.key)"
											/>
											<Input
												:id="field.key"
												v-model.number="formData[field.key]"
												type="number"
												:min="field.min"
												:max="field.max"
												:step="field.step"
												:placeholder="field.placeholder"
												:required="field.required"
												class="mt-1 h-11"
											/>
										</div>

										<div
											v-else-if="
												props.dataType === 'assessments' &&
												(field.key === 'scale_min' ||
													field.key === 'scale_max') &&
												showScaleFields
											"
										>
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
												:required="field.required"
												:description="getFieldDescription(field.key)"
											/>
											<Input
												:id="field.key"
												v-model.number="formData[field.key]"
												type="number"
												:min="field.min"
												:max="field.max"
												:step="field.step || 1"
												:placeholder="field.placeholder"
												:required="field.required"
												:readonly="true"
												class="mt-1 h-11 bg-muted cursor-not-allowed"
											/>
											<p class="mt-1 text-sm leading-6 text-muted-foreground">
												Fixed at {{ field.key === "scale_min" ? "1" : "4" }} for
												standardized 1-4 scale
											</p>
										</div>

										<div
											v-else-if="
												props.dataType === 'assessments' &&
												field.key.startsWith('scale_label_') &&
												showScaleFields
											"
										>
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
												:required="field.required"
												:description="getFieldDescription(field.key)"
											/>
											<Input
												:id="field.key"
												v-model="formData[field.key]"
												type="text"
												:placeholder="getDefaultScaleLabel(field.key)"
												:required="field.required"
												class="mt-1 h-11"
											/>
											<p class="mt-1 text-sm leading-6 text-muted-foreground">
												Label for scale value {{ field.key.split('_')[2] }}
											</p>
										</div>

										<div v-else-if="field.type === 'switch'">
											<div class="flex min-h-11 items-center gap-3">
												<Switch :id="field.key" v-model="formData[field.key]" />
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
											/>
											</div>
										</div>

										<div v-else-if="field.type === 'json'">
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
												:required="field.required"
												:description="getFieldDescription(field.key)"
											/>
											<Textarea
												:id="field.key"
												v-model="jsonFields[field.key]"
												:rows="field.rows || 4"
												:placeholder="field.placeholder"
												class="mt-1 font-mono text-sm"
												@blur="validateJson(field.key)"
											/>
											<p
												v-if="jsonErrors[field.key]"
												class="mt-1 text-sm text-destructive"
											>
												{{ jsonErrors[field.key] }}
											</p>
										</div>

										<div v-else-if="field.type === 'select-with-create'">
											<FormFieldLabel
												:field-key="field.key"
												:label="field.label"
												:required="field.required"
												:description="getFieldDescription(field.key)"
											/>
											<div class="mt-1 flex gap-2">
												<Select v-model="formData[field.key]" class="flex-1 min-w-0">
													<SelectTrigger class="h-11 w-full">
														<SelectValue :placeholder="'Select ' + field.label" />
													</SelectTrigger>
													<SelectContent>
														<SelectItem
															v-for="option in dropdownOptions[field.key]"
															:key="String(option[field.valueKey || 'value'])"
															:value="String(option[field.valueKey || 'value'])"
														>
															{{ option[field.labelKey || 'label'] }}
														</SelectItem>
													</SelectContent>
												</Select>
												<Button
													type="button"
													variant="outline"
													@click="openQuickCreate(field.createType || '', field.key)"
													:aria-label="`Create a new ${field.label}`"
													class="h-11 w-11 flex-shrink-0"
												>
													<Plus class="h-4 w-4" />
												</Button>
											</div>
										</div>

										<p
											v-if="needsValidation(field.key)"
											class="mt-1 text-sm leading-6"
											:class="getValidationTone(field.key)"
											role="status"
											aria-live="polite"
										>
											{{ getValidationMessage(field.key, field.label) }}
										</p>
									</div>
								</div>
							</div>

							<div
								v-if="validationErrors.length > 0"
								class="space-y-1 rounded-md border border-destructive/20 bg-destructive/5 px-3 py-2 text-sm leading-6 text-destructive"
							>
								<p class="font-medium">Please fix the following:</p>
								<ul class="list-disc space-y-1 pl-5">
									<li v-for="error in validationErrors" :key="error">
										{{ error }}
									</li>
								</ul>
							</div>
						</div>
					</div>

					<div
						class="sticky bottom-0 z-20 border-t bg-background/95 px-4 py-4 backdrop-blur supports-[backdrop-filter]:bg-background/80 sm:px-6"
					>
						<p
							v-if="showDefaultActiveNote"
							class="mb-2 text-xs leading-5 text-muted-foreground"
						>
							New records are active by default.
						</p>
						<DialogFooter class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
							<Button
								type="button"
								variant="outline"
								@click="closeModal"
								:disabled="isSaving"
								class="h-11 w-full sm:w-auto"
							>
								Cancel
							</Button>
								<Button
									type="submit"
									:disabled="isSaving || isValidationLoading || isGeneratingSystemId"
									class="h-11 w-full sm:min-w-[120px] sm:w-auto"
								>
								<Loader2 v-if="isSaving" class="mr-2 h-4 w-4 animate-spin" />
								{{ isSaving ? "Saving..." : submitLabel }}
							</Button>
						</DialogFooter>
					</div>
				</form>

			<!-- Quick Create Modal -->
			<QuickCreateModal
				:is-open="showQuickCreate"
				:type="quickCreateType || 'problem_type'"
				@close="closeQuickCreate"
				@created="handleQuickCreateSuccess"
			/>
		</DialogContent>
	</Dialog>
</template>

<script setup lang="ts">
import { ref, computed, watch, reactive, nextTick } from "vue";
import { X, Loader2, Plus } from "lucide-vue-next";
import { useSupabase } from "@/composables/useSupabase";

// shadcn-vue components
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import QuickCreateModal from "@/components/admin/QuickCreateModal.vue";
import AsyncSearchSelect from "@/components/admin/AsyncSearchSelect.vue";
import FormFieldLabel from "@/components/admin/FormFieldLabel.vue";
import { getFormSchema } from "@/config/formSchemas";
import {
	generateActionId,
	generateSuggestionId,
} from "@/utils/commonIdGenerator";

// Migrated types
const USE_SUPABASE_FOR = [
	"problem_types",
	"problems",
	"assessments",
	"suggestions",
	"feedback_prompts",
	"next_actions",
	"training_examples",
];

// Supabase client
const { supabase } = useSupabase();

// Props
const props = defineProps({
	isOpen: {
		type: Boolean,
		default: false,
	},
	dataType: {
		type: String,
		required: true,
	},
	item: {
		type: Object,
		default: null,
	},
});

// Emits
const emit = defineEmits(["close", "save"]);

// Reactive data
const formData = reactive<Record<string, any>>({});
const jsonFields = reactive<Record<string, any>>({});
const jsonErrors = reactive<Record<string, any>>({});
const newTag = reactive<Record<string, any>>({});
const isSaving = ref(false);
const isGeneratingSystemId = ref(false);
const systemIdError = ref("");
const initialFormSnapshot = ref("");

// Validation state
const validationStatus = reactive<Record<string, any>>({
	type_name: { checked: false, exists: false, loading: false, error: "" },
	category_id: { checked: false, exists: false, loading: false, error: "" },
	sub_category_id: { checked: false, exists: false, loading: false, error: "" },
	question_id: { checked: false, exists: false, loading: false, error: "" },
});

const fieldTouched = reactive<Record<string, boolean>>({});
const hasAttemptedSave = ref(false);

// Dropdown options and quick create state
const dropdownOptions = reactive<Record<string, any>>({
	category: [] as any[],
	sub_category_id: [] as any[],
});
const showQuickCreate = ref(false);
const quickCreateType = ref<string | null>(null);
const quickCreateFieldKey = ref<string | null>(null);
const optionalSectionsOpen = reactive<Record<string, boolean>>({
	optional: false,
});

// Computed properties
const isEditing = computed(() => !!props.item);
const validationErrors = ref<string[]>([]);
const isValidationLoading = computed(() =>
	Object.values(validationStatus).some((status: any) => status.loading),
);

// Response type helpers (assessments)
const selectedResponseType = computed(() => formData.response_type);
const showScaleFields = computed(
	() =>
		props.dataType === "assessments" && selectedResponseType.value === "scale"
);

const dataTypeLabel = computed(() => {
	const labels: Record<string, string> = {
		problems: "Problem Category",
		assessments: "Assessment Question",
		suggestions: "Suggestion",
		feedback_prompts: "Feedback Prompt",
		next_actions: "Next Action",
		training_examples: "Fine-tuning Example",
		problem_types: "Problem Type",
	};
	return labels[props.dataType] || "Item";
});

const modalDescription = computed(() => {
	const content: Record<
		string,
		{ create: string; edit: string }
	> = {
		suggestions: {
			create:
				"Add therapeutic guidance linked to a subcategory so downstream prompts stay consistent.",
			edit: "Update therapeutic guidance text and linkage details.",
		},
		next_actions: {
			create:
				"Define what should happen next so workflow transitions stay predictable.",
			edit: "Update action behavior, naming, and operational details.",
		},
		feedback_prompts: {
			create:
				"Create a follow-up prompt to guide user responses after suggestions.",
			edit: "Update prompt wording and follow-up linkage.",
		},
	};

	const current = content[props.dataType];
	if (current) {
		return isEditing.value ? current.edit : current.create;
	}

	return isEditing.value ? "Update this record." : "Create a new record.";
});

const submitLabel = computed(() => {
	if (isEditing.value) {
		if (props.dataType === "suggestions") return "Save Suggestion";
		if (props.dataType === "next_actions") return "Save Action";
		return "Update";
	}

	if (props.dataType === "suggestions") return "Create Suggestion";
	if (props.dataType === "next_actions") return "Create Action";
	return "Create";
});

const showDefaultActiveNote = computed(
	() =>
		!isEditing.value &&
		(props.dataType === "suggestions" || props.dataType === "next_actions"),
);

const useSingleColumnLayout = computed(
	() =>
		!isEditing.value &&
		(props.dataType === "suggestions" || props.dataType === "next_actions"),
);

const formFields = computed(() => {
	return getFormSchema(props.dataType);
});

const isSubCategoryAsyncField = (field: { key: string }) =>
	field.key === "sub_category_id" &&
	(props.dataType === "assessments" || props.dataType === "suggestions");

const isAutoGeneratedIdField = (fieldKey: string) =>
	(props.dataType === "suggestions" && fieldKey === "suggestion_id") ||
	(props.dataType === "next_actions" && fieldKey === "action_id");

const isHiddenField = (field: { key: string }) => {
	// Keep create flow simple for system-managed fields.
	// IDs are auto-generated and is_active defaults to true.
	if (
		!isEditing.value &&
		(
			(props.dataType === "next_actions" &&
				(field.key === "action_id" || field.key === "is_active")) ||
			(props.dataType === "suggestions" &&
				(field.key === "suggestion_id" || field.key === "is_active"))
		)
	) {
		return true;
	}

	return false;
};

type FormSectionKey = "core" | "relationships" | "technical";
type ExtendedFormSectionKey = FormSectionKey | "optional";

const sectionDefinitions: Record<ExtendedFormSectionKey, { title: string }> = {
	core: {
		title: "Main information",
	},
	relationships: {
		title: "Linked records",
	},
	optional: {
		title: "Optional details",
	},
	technical: {
		title: "System details",
	},
};

const fieldDescriptions: Record<string, Record<string, string>> = {
	suggestions: {
		suggestion_id: "System-generated identifier for auditing and references.",
		sub_category_id:
			"Choose the subcategory this guidance belongs to.",
		cluster: "Optional grouping label for reporting or segmentation.",
		suggestion_text: "The therapeutic guidance text shown to users.",
		evidence_base: "Optional therapeutic model or evidence basis for this suggestion.",
		is_active: "Turn off to hide this suggestion from live workflows.",
	},
	next_actions: {
		action_id: "System-generated identifier for this action.",
		action_text: "Describe what operators or the system should do next.",
		is_active: "Turn off to prevent this action from being used.",
	},
};

const getFieldDescription = (fieldKey: string) =>
	fieldDescriptions[props.dataType]?.[fieldKey] || "";

const isOptionalField = (field: { key: string; type: string }) => {
	if (props.dataType === "suggestions") {
		return field.key === "cluster" || field.key === "evidence_base";
	}

	return false;
};

const isTechnicalField = (field: { key: string; type: string }) => {
	if (field.type === "json") return true;
	if (field.key === "is_active") return true;
	if (isAutoGeneratedIdField(field.key)) return true;

	if (props.dataType === "problem_types" && field.key === "category_id") return true;
	if (props.dataType === "suggestions" && field.key === "suggestion_id") return true;
	if (props.dataType === "assessments") {
		if (field.key === "question_id") return true;
		if (
			field.key === "scale_min" ||
			field.key === "scale_max" ||
			field.key.startsWith("scale_label_")
		) {
			return true;
		}
	}
	if (props.dataType === "feedback_prompts" && field.key === "prompt_id") return true;
	if (props.dataType === "next_actions" && field.key === "action_id") return true;
	if (props.dataType === "training_examples" && field.key === "example_id") return true;

	return false;
};

const isRelationshipField = (field: { key: string; type: string }) => {
	if (field.type === "select-with-create") return true;
	if (isSubCategoryAsyncField(field)) return true;
	if (props.dataType === "assessments" && field.key === "sub_category_id") return true;
	if (props.dataType === "feedback_prompts" && field.key === "next_action_id") return true;
	if (props.dataType === "problems" && field.key === "sub_category_id") return true;
	if (props.dataType === "problems" && field.key === "category") return true;

	return false;
};

const getFieldSection = (field: { key: string; type: string }) => {
	if (isOptionalField(field)) return "optional" as const;
	if (isTechnicalField(field)) return "technical" as const;
	if (isRelationshipField(field)) return "relationships" as const;
	return "core" as const;
};

const formSections = computed(() => {
	const buckets: Record<ExtendedFormSectionKey, any[]> = {
		core: [],
		relationships: [],
		optional: [],
		technical: [],
	};

	formFields.value.filter((field) => !isHiddenField(field)).forEach((field) => {
		buckets[getFieldSection(field)].push(field);
	});

	return (["core", "relationships", "optional", "technical"] as const)
		.map((key) => ({
			key,
			...sectionDefinitions[key],
			fields: buckets[key],
		}))
		.filter((section) => section.fields.length > 0);
});

const isOptionalSectionOpen = (sectionKey: string) =>
	Boolean(optionalSectionsOpen[sectionKey]);

const toggleOptionalSection = (sectionKey: string) => {
	optionalSectionsOpen[sectionKey] = !isOptionalSectionOpen(sectionKey);
};

// Helper to check if field needs validation
const needsValidation = (fieldKey: string): boolean => {
	return (
		(props.dataType === "problem_types" &&
			(fieldKey === "type_name" || fieldKey === "category_id")) ||
		(props.dataType === "problems" && fieldKey === "sub_category_id") ||
		(props.dataType === "assessments" && fieldKey === "question_id")
	);
};

const markFieldTouched = (fieldKey: string) => {
	fieldTouched[fieldKey] = true;
};

const handleValidationBlur = async (fieldKey: string) => {
	markFieldTouched(fieldKey);

	if (needsValidation(fieldKey) && formData[fieldKey]) {
		await checkForDuplicate(fieldKey);
	}
};

const getValidationTone = (fieldKey: string) => {
	const status = validationStatus[fieldKey];
	if (status?.error || status?.exists) return "text-destructive";
	if (status?.checked && !status?.exists) return "text-emerald-600";
	return "text-muted-foreground";
};

const getValidationMessage = (fieldKey: string, label: string) => {
	const status = validationStatus[fieldKey];
	const value = formData[fieldKey];
	const touched = fieldTouched[fieldKey] || hasAttemptedSave.value;

	if (!needsValidation(fieldKey) || !touched) {
		return "";
	}

	if (status?.error) {
		return status.error;
	}

	if (!value) {
		return `${label} is required.`;
	}

	if (status?.loading) {
		return "Checking availability...";
	}

	if (status?.checked && status?.exists) {
		return `${label} already exists. Please choose a different one.`;
	}

	if (status?.checked && !status?.exists) {
		return "Available.";
	}

	return "Will be checked automatically when you save.";
};

const normalizeForSnapshot = (value: any): any => {
	if (Array.isArray(value)) {
		return value.map((item) => normalizeForSnapshot(item));
	}

	if (value && typeof value === "object") {
		const normalized: Record<string, any> = {};
		Object.keys(value)
			.sort()
			.forEach((key) => {
				const current = value[key];
				if (current !== undefined) {
					normalized[key] = normalizeForSnapshot(current);
				}
			});
		return normalized;
	}

	return value;
};

const createFormSnapshot = () =>
	JSON.stringify(
		normalizeForSnapshot({
			formData,
			jsonFields,
		}),
	);

const hasUnsavedChanges = computed(
	() => createFormSnapshot() !== initialFormSnapshot.value,
);

const ensureAutoGeneratedIds = async () => {
	if (isEditing.value) return;

	if (
		props.dataType !== "suggestions" &&
		props.dataType !== "next_actions"
	) {
		return;
	}

	isGeneratingSystemId.value = true;
	systemIdError.value = "";

	try {
		if (props.dataType === "suggestions" && !formData.suggestion_id) {
			formData.suggestion_id = await generateSuggestionId(supabase);
		}

		if (props.dataType === "next_actions" && !formData.action_id) {
			formData.action_id = await generateActionId(supabase);
		}
	} catch (error) {
		console.error("Auto ID generation error:", error);
		systemIdError.value =
			"Unable to generate an ID automatically. Please close and try again.";
	} finally {
		isGeneratingSystemId.value = false;
	}
};

// Methods
const closeModal = (force = false) => {
	if (!isSaving.value || force) {
		if (
			!force &&
			hasUnsavedChanges.value &&
			typeof window !== "undefined" &&
			!window.confirm("Discard unsaved changes?")
		) {
			return;
		}

		resetForm();
		emit("close");
	}
};

const resetForm = () => {
	[formData, jsonFields, jsonErrors, newTag].forEach((obj) =>
		Object.keys(obj).forEach((k) => delete obj[k])
	);
	validationErrors.value = [];
	isSaving.value = false;
	isGeneratingSystemId.value = false;
	systemIdError.value = "";
	hasAttemptedSave.value = false;
	Object.keys(fieldTouched).forEach((k) => delete fieldTouched[k]);
	optionalSectionsOpen.optional = false;
	// Reset validation status
	["type_name", "category_id", "sub_category_id", "question_id"].forEach(
		(k) => {
			validationStatus[k] = {
				checked: false,
				exists: false,
				loading: false,
				error: "",
			};
		}
	);
};

const initializeForm = async () => {
	resetForm();

	// Fetch dropdown options for select-with-create fields
	formFields.value.forEach((field) => {
		if (field.type === "select-with-create" && field.fetchEndpoint) {
			fetchDropdownOptions(field.fetchEndpoint as string, field.key);
		}
		if (
			props.dataType === "assessments" &&
			field.key === "sub_category_id" &&
			field.type === "select"
		) {
			fetchDropdownOptions(
				"/dataset/problems/subcategories",
				"sub_category_id"
			);
		}
	});

	if (props.item) {
		// Edit mode - populate with existing data
		Object.assign(formData, structuredClone(props.item));

		// Handle JSON fields
		formFields.value.forEach((field) => {
			if (field.type === "json" && props.item[field.key]) {
				jsonFields[field.key] = JSON.stringify(props.item[field.key], null, 2);
			}
		});

		// Handle scale_labels for assessments
		if (props.dataType === "assessments" && props.item.scale_labels) {
			formData.scale_label_1 = props.item.scale_labels["1"] || "Not at all";
			formData.scale_label_2 = props.item.scale_labels["2"] || "A little";
			formData.scale_label_3 = props.item.scale_labels["3"] || "Quite a bit";
			formData.scale_label_4 = props.item.scale_labels["4"] || "Very much";
		}

	if (props.dataType === "suggestions") {
		optionalSectionsOpen.optional = Boolean(
			props.item.cluster || props.item.evidence_base,
		);
	}
	} else {
		// Create mode - set defaults
		formFields.value.forEach((field) => {
			if (field.type === "switch") {
				formData[field.key] = true;
			} else if (field.type === "tags") {
				formData[field.key] = [];
			} else if (field.type === "json") {
				jsonFields[field.key] = "";
			}
		});

		// Set is_active to true by default for new items
		formData.is_active = true;

		// Set default scale labels for assessments
		if (props.dataType === "assessments") {
			formData.scale_label_1 = "Not at all";
			formData.scale_label_2 = "A little";
			formData.scale_label_3 = "Quite a bit";
			formData.scale_label_4 = "Very much";
		}

		await ensureAutoGeneratedIds();
		optionalSectionsOpen.optional = false;
	}

	initialFormSnapshot.value = createFormSnapshot();
};

const validateJson = (fieldKey: string) => {
	const value = jsonFields[fieldKey];
	if (!value) {
		delete jsonErrors[fieldKey];
		return;
	}

	try {
		const parsed = JSON.parse(value);
		formData[fieldKey] = parsed;
		delete jsonErrors[fieldKey];
	} catch (error) {
		jsonErrors[fieldKey] = "Invalid JSON format";
	}
};

const addTag = (fieldKey: string) => {
	const value = newTag[fieldKey]?.trim();
	if (value && !formData[fieldKey]?.includes(value)) {
		if (!formData[fieldKey]) {
			formData[fieldKey] = [];
		}
		formData[fieldKey].push(value);
		newTag[fieldKey] = "";
	}
};

const removeTag = (fieldKey: string, index: number) => {
	if (formData[fieldKey] && Array.isArray(formData[fieldKey])) {
		(formData[fieldKey] as any[]).splice(index, 1);
	}
};

const checkForDuplicate = async (fieldKey: string) => {
	validationStatus[fieldKey].loading = true;
	validationStatus[fieldKey].error = "";

	try {
		const value = formData[fieldKey];
		if (!value) {
			validationStatus[fieldKey].loading = false;
			return;
		}

		if (USE_SUPABASE_FOR.includes(props.dataType)) {
			let query = supabase
				.from(props.dataType)
				.select("id", { count: "exact" })
				.eq(fieldKey, value);
			if (props.item?.id) query = query.neq("id", props.item.id);
			const { count, error } = await query;
			if (error) throw error;
			validationStatus[fieldKey].checked = true;
			validationStatus[fieldKey].exists = (count || 0) > 0;
			return !validationStatus[fieldKey].exists;
		}

		// Legacy API check - build URL based on field
		const config = useRuntimeConfig();
		const base =
			config.public.adminApiUrl || "http://localhost:8000/api/v1/admin";
		const urlMap: Record<string, string> = {
			type_name: `/dataset/validate/problem_types/${encodeURIComponent(value)}`,
			question_id: `/dataset/validate/assessments/question_id/${encodeURIComponent(
				value
			)}`,
			category_id: `/dataset/validate/problem_types/category_id/${encodeURIComponent(
				value
			)}`,
			sub_category_id: `/dataset/validate/problems/sub_category_id/${encodeURIComponent(
				value
			)}`,
		};
		let url = base + (urlMap[fieldKey] || "");
		if (props.item?.id) url += `?exclude_id=${props.item.id}`;

		const response = (await $fetch(url)) as any;
		validationStatus[fieldKey].checked = true;
		validationStatus[fieldKey].exists = response.data.exists;
		return !validationStatus[fieldKey].exists;
	} catch (error) {
		console.error("Validation error:", error);
		validationStatus[fieldKey].checked = false;
		validationStatus[fieldKey].exists = false;
		validationStatus[fieldKey].error =
			"Unable to check availability right now. Please try again.";
		return false;
	} finally {
		validationStatus[fieldKey].loading = false;
	}
};

const fetchDropdownOptions = async (endpoint: string, key: string) => {
	try {
		// If endpoint resembles a migrated type, use Supabase
		const migratedTable = USE_SUPABASE_FOR.find((t) => endpoint.includes(t));
		if (migratedTable) {
			const { data, error } = await supabase
				.from(migratedTable)
				.select("*")
				.order(migratedTable === "problem_types" ? "type_name" : "created_at", {
					ascending: true,
				});

			if (error) throw error;
			dropdownOptions[key] = data || [];
			return;
		}

		const config = useRuntimeConfig();
		const adminApiUrl =
			config.public.adminApiUrl || "http://localhost:8000/api/v1/admin";
		const url = `${adminApiUrl}${endpoint}`;

		const response = (await $fetch(url)) as any;
		dropdownOptions[key] = response.data?.items || [];
	} catch (error) {
		console.error(`Error fetching ${key} options:`, error);
		dropdownOptions[key] = [];
	}
};

const openQuickCreate = (type: string, fieldKey: string) => {
	quickCreateType.value = type;
	quickCreateFieldKey.value = fieldKey;
	showQuickCreate.value = true;
};

const closeQuickCreate = () => {
	showQuickCreate.value = false;
	quickCreateType.value = null;
	quickCreateFieldKey.value = null;
};

const handleQuickCreateSuccess = async (newItem: any) => {
	// Refresh the dropdown options
	const field = formFields.value.find(
		(f) => f.key === quickCreateFieldKey.value
	);
	if (field && field.fetchEndpoint) {
		await fetchDropdownOptions(field.fetchEndpoint as string, field.key);

		// Auto-select the newly created item
		if (field.createType === "problem_type") {
			formData[field.key] = newItem.type_name;
		}
	}

	closeQuickCreate();
};

const validateForm = async () => {
	hasAttemptedSave.value = true;
	const errors: string[] = [];

	if (
		!isEditing.value &&
		(props.dataType === "suggestions" || props.dataType === "next_actions")
	) {
		await ensureAutoGeneratedIds();
	}

	if (systemIdError.value) {
		errors.push(systemIdError.value);
	}

	// ID format validations
	const idFormats: Record<string, { pattern: RegExp; format: string }> = {
			suggestion_id: {
				pattern: /^(S_\d{4,}|SUG_\d{3,4}|S_[A-Z]{2,4}_\d{3,4})$/i,
				format: "S_#### or S_DOMAIN_### (e.g., S_0001 or S_STR_001)",
			},
		prompt_id: {
			pattern: /^P_[A-Z]{2,4}_\d{3,4}$/,
			format: "P_DOMAIN_### (e.g., P_STR_001)",
		},
		action_id: {
			pattern: /^A_\d{3,4}$/,
			format: "A_### or A_#### (e.g., A_001)",
		},
		example_id: {
			pattern: /^E_\d{3,4}$/,
			format: "E_### or E_#### (e.g., E_001)",
		},
	};

	for (const field of formFields.value) {
		if (field.required && !formData[field.key]) {
			errors.push(`${field.label} is required`);
		}
		if (field.type === "json" && jsonErrors[field.key]) {
			errors.push(`${field.label}: ${jsonErrors[field.key]}`);
		}

		// ID format validation
		const idFormat = idFormats[field.key];
		if (
			idFormat &&
			formData[field.key] &&
			!idFormat.pattern.test(formData[field.key])
		) {
			errors.push(`${field.label} must be in format: ${idFormat.format}`);
		}

		// Scale validation for assessments
		if (
			props.dataType === "assessments" &&
			field.key === "response_type" &&
			formData.response_type === "scale"
		) {
			if (formData.scale_min !== 1 || formData.scale_max !== 4)
				errors.push("Scale questions must use 1-4 range");
			[
				"scale_label_1",
				"scale_label_2",
				"scale_label_3",
				"scale_label_4",
			].forEach((labelKey) => {
				if (!formData[labelKey] || formData[labelKey].trim() === "") {
					errors.push(
						`${labelKey.replace("_", " ")} is required for scale questions`
					);
				}
			});
		}

		// Duplicate validation using needsValidation helper
		if (needsValidation(field.key)) {
			const status = validationStatus[field.key];
			const skipCheck = field.key === "sub_category_id" && isEditing.value;
			if (!skipCheck && formData[field.key]) {
				const isUnique = await checkForDuplicate(field.key);
				if (!isUnique) {
					if (status?.error) {
						errors.push(status.error);
					} else if (status?.exists) {
						errors.push(
							`${field.label} already exists. Please choose a different one.`
						);
					} else {
						errors.push(
							`Unable to verify ${field.label}. Please try again.`
						);
					}
				}
			}
		}
	}

	validationErrors.value = errors;
	return errors.length === 0;
};

const saveItem = async () => {
	if (!(await validateForm())) {
		return;
	}

	isSaving.value = true;

	try {
		// Process JSON fields
		formFields.value.forEach((field) => {
			if (field.type === "json" && jsonFields[field.key]) {
				validateJson(field.key);
			}
		});

		// For assessments: boolean defaults
		if (
			props.dataType === "assessments" &&
			formData.response_type === "boolean"
		) {
			if (!Array.isArray(formData.options) || formData.options.length === 0) {
				formData.options = ["Yes", "No"];
			}
		}

		// For assessments: scale processing
		if (
			props.dataType === "assessments" &&
			formData.response_type === "scale"
		) {
			// Set fixed scale values
			formData.scale_min = 1;
			formData.scale_max = 4;

			// Construct scale_labels object from individual fields
			formData.scale_labels = {
				"1": formData.scale_label_1 || "Not at all",
				"2": formData.scale_label_2 || "A little",
				"3": formData.scale_label_3 || "Quite a bit",
				"4": formData.scale_label_4 || "Very much",
			};

			// Remove individual label fields from submission
			delete formData.scale_label_1;
			delete formData.scale_label_2;
			delete formData.scale_label_3;
			delete formData.scale_label_4;
		} else if (props.dataType === "assessments") {
			// For non-scale questions, remove scale fields
			delete formData.scale_min;
			delete formData.scale_max;
			delete formData.scale_labels;
			delete formData.scale_label_1;
			delete formData.scale_label_2;
			delete formData.scale_label_3;
			delete formData.scale_label_4;
		}

		// Emit save event
		emit("save", { ...formData });

		// Close modal after successful save
		closeModal(true);
	} catch (error) {
		console.error("Save error:", error);
		validationErrors.value = [
			"An error occurred while saving. Please try again.",
		];
	} finally {
		isSaving.value = false;
	}
};

// Watchers
watch(
	() => props.isOpen,
	async (newValue) => {
		if (newValue) {
			// Use nextTick to ensure props.item is fully available
			await nextTick();
			initializeForm();
		}
	}
);

watch(
	() => props.item,
	() => {
		if (props.isOpen) {
			initializeForm();
		}
	},
	{ deep: true }
);

// Clear unrelated fields when response_type changes
watch(
	() => formData.response_type,
	() => {
		if (props.dataType !== "assessments") return;
		if (formData.response_type !== "scale") {
			delete formData.scale_min;
			delete formData.scale_max;
		}
	}
);

// Watch for changes in type_name to reset validation
watch(
	() => formData.type_name,
	() => {
		if (props.dataType === "problem_types") {
			validationStatus.type_name.checked = false;
			validationStatus.type_name.exists = false;
			validationStatus.type_name.error = "";
			validationStatus.type_name.loading = false;
		}
	}
);

watch(
	() => formData.question_id,
	() => {
		if (props.dataType === "assessments") {
			validationStatus.question_id.checked = false;
			validationStatus.question_id.exists = false;
			validationStatus.question_id.error = "";
			validationStatus.question_id.loading = false;
		}
	}
);

watch(
	() => formData.category_id,
	() => {
		if (props.dataType === "problem_types") {
			validationStatus.category_id.checked = false;
			validationStatus.category_id.exists = false;
			validationStatus.category_id.error = "";
			validationStatus.category_id.loading = false;
		}
	}
);

watch(
	() => formData.sub_category_id,
	() => {
		if (props.dataType === "problems") {
			validationStatus.sub_category_id.checked = false;
			validationStatus.sub_category_id.exists = false;
			validationStatus.sub_category_id.error = "";
			validationStatus.sub_category_id.loading = false;
		}
	}
);

// Helper function to get default scale labels
const getDefaultScaleLabel = (fieldKey: string) => {
	const defaults: Record<string, string> = {
		scale_label_1: "Not at all",
		scale_label_2: "A little",
		scale_label_3: "Quite a bit",
		scale_label_4: "Very much",
	};
	return defaults[fieldKey] || "";
};
</script>
